name: Build & Test

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: lint
        run: |
          npm run lint

      - name: Build
        run: |
          npm install
          npm run build

      - name: Run Tests
        run: |
          npm run tes
